"""Application-wide constants with units."""

MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024      # 100 MB
BATCH_IMPORT_MAX_FILES = 100
LARGE_CHUNK_MAX_TOKENS = 2048
SMALL_CHUNK_MAX_TOKENS = 512
OVERLAP_TOKENS = 100
MAX_RETRY_COUNT = 3
OUTBOX_BATCH_SIZE = 50
POLLER_INTERVAL_SECONDS = 5
HEARTBEAT_INTERVAL_SECONDS = 30
HEARTBEAT_TIMEOUT_SECONDS = 120
ORPHAN_CHECK_INTERVAL_SECONDS = 300
REDIS_LOCK_TTL_SECONDS = 60
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_SECONDS = 30
API_RATE_LIMIT_UPLOAD = "5/second"
API_RATE_LIMIT_GLOBAL = "10/second"
