"""Application-wide constants with units."""

MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024      # 100 MB
BATCH_IMPORT_MAX_FILES = 100
LARGE_CHUNK_MAX_TOKENS = 2048
SMALL_CHUNK_MAX_TOKENS = 512
OVERLAP_TOKENS = 100
MAX_RETRY_COUNT = 3
OUTBOX_BATCH_SIZE = 50
POLLER_INTERVAL_SECONDS = 5
HEARTBEAT_INTERVAL_SECONDS = 30
HEARTBEAT_TIMEOUT_SECONDS = 120
ORPHAN_CHECK_INTERVAL_SECONDS = 300
REDIS_LOCK_TTL_SECONDS = 60
CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
CIRCUIT_BREAKER_RECOVERY_SECONDS = 30
API_RATE_LIMIT_UPLOAD = "5/second"
API_RATE_LIMIT_GLOBAL = "10/second"

# --- Indexing ---
INDEX_BATCH_SIZE_DEFAULT = 200
INDEX_BATCH_TIMEOUT_DEFAULT = 3.0
INDEX_BUFFER_MAX_SIZE = 2000
INDEX_DLQ_MAX_RETRY = 10
INDEX_MAX_POLL_RECORDS = 500
INDEX_EMBEDDING_DIM = 384
INDEX_EMBEDDING_MODEL = "all-MiniLM-L6-v2"
INDEX_METRICS_PORT_DEFAULT = 9090
INDEX_SUB_BATCH_SIZE = 10
INDEX_SINGLE_MAX_RETRIES = 5
INDEX_BATCH_BACKOFF_BASE = 5  # seconds: 5, 10, 20
INDEX_SINGLE_BACKOFF_BASE = 2  # seconds: 2, 4, 8, 16, 32
INDEX_HEALTH_PORT = 9090

# --- GraphRAG ---
GRAPHRAG_LLM_MAX_TOKENS = 800
GRAPHRAG_ENTITY_SIMILARITY_THRESHOLD = 0.85
GRAPHRAG_POSTPROCESS_MAX_ENTITIES = 2000
GRAPHRAG_REBUILD_HOUR = 3
GRAPHRAG_REBUILD_LOOKBACK_HOURS = 24
GRAPHRAG_DLQ_MAX_RETRY = 10
GRAPHRAG_REDIS_TTL_SECONDS = 3600
GRAPHRAG_EMBEDDING_BATCH_SIZE = 32
GRAPHRAG_TX_TIMEOUT_SECONDS = 15
GRAPHRAG_MERGE_RETRY_BACKOFF = 0.5
GRAPHRAG_MAX_TOKENS_PER_BATCH = 100000

# --- RAPTOR ---
RAPTOR_MAX_DEPTH = 3
RAPTOR_STOP_CLUSTERING_TOKENS = 1000
RAPTOR_BUILD_TIMEOUT_MINUTES = 30
RAPTOR_REDIS_TTL_SECONDS = 3600
RAPTOR_GMM_PROB_THRESHOLD = 0.2
RAPTOR_UMAP_N_COMPONENTS = 5
RAPTOR_TARGET_TOKENS_PER_CLUSTER = 1500
RAPTOR_LLM_MAX_TOKENS = 600
RAPTOR_LLM_BACKUP_TIMEOUT = 30
RAPTOR_KAFKA_TOPIC = "knowledge.raptor.summaries"

# --- Search ---
RERANKER_MODEL = "BAAI/bge-reranker-v2-m3"
SEARCH_MIN_SCORE_THRESHOLD = 0.01
SEARCH_FUSION_WEIGHTS = {
    "fact":    {"bm25": 0.6, "vector": 0.3, "graph": 0.1},
    "concept": {"bm25": 0.1, "vector": 0.6, "graph": 0.3},
    "rel":     {"bm25": 0.2, "vector": 0.3, "graph": 0.5},
}
SEARCH_DEFAULT_WEIGHTS = {"bm25": 0.2, "vector": 0.5, "graph": 0.3}
SEARCH_ABSOLUTE_MIN_THRESHOLD = 0.4
SEARCH_RERANKER_THRESHOLD = 0.3
